# Site settings
# These are used to personalize your new site.
title: Meagan Porter # your name here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Technology in Computer-Science (class of 2021)
  <br /><br />
  <a href="meaganbporter.github.io/pdf/finalresume.pdf" target = "_blank">View My Resume</a>
repository: "meaganbporter/meaganbporter.github.io"
github_username:  meaganbporter # update with your username

# Build setting
theme: jekyll-theme-minimal

